language: python
python: 2.7
env:
- TOXENV=py27
- TOXENV=py34
install:
  - pip install -U tox
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: UYI1eP3KgFvr3Psd9GMMcnidyvhjmbRM1M/XDRXEttNWdXmEkCfEJlsYrSGJzkG6VH3H2uN32w84SMTLVyttqlXdCKLXg/jUVqI1XQMXqGF10G2HdiFjAQLivWf3fMBo2KphEZtC9vfbJCCSnRwU3SNqi1FSStbVviXuMjCT43bEECYqK9BksiZo5Eb57nVuFbYCZJ7ZX403ZUzoUBm4MWA9CE6+cn5abF46A5BJ9UlJxtpc0TmcXkFsx2OyxX+h63xLsKm3hFvbtjqz4cL+Z/xrx60IlPYBBOvtVIFkeLfmrqfP9eG5Sxu/YHqixTIaylR40P5DqSIuTJN+4Z7bbl0sdiHd3u4DJhXhr5ofkreSsS2cigk5Ttwg126/dV8PNa4JHEqP8atDC6n28B1nKhjeSTNa/DctgmJWSSCzFDnWAfWWsZwBK6me5SyzsF1gSVcLLWWvlYGDELVnuhzp82/+AgMAYR600t4zIlJKfiCNG29Mt1FkaRDmcePiD7+l/VjeJaQVaP2DD14UGasFmG1r4OMrVKHeuvD856NjHWOrETKxhklmFvJw5gpMA2zircqAt3XIcAXwQPl49jFcx+vyfOvEVFwkLeemehPADgWN8kDKejGqVEasK/fjomMsO+BPOr/t1RGjFHAH/bHEL+1vN6pQzL0yNnC/vRtuAG8=
  on:
    tags: true
    repo: scrapinghub/scrapy-mosquitera
    condition: "$TOXENV == py27"
